name: Lint Go

on:
  pull_request:
    paths:
      - cmd/arxiv-cli/*.go
      - go.mod
      - go.sum
      - internal/download/*.go

jobs:
  lint-go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Set up golangci
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Format
        run: make format-go

      - name: Lint
        run: make lint-go
